## Importing Libraries

In [30]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import StratifiedKFold


##  Load the dataset

In [31]:

df = pd.read_csv('zoo.csv',header=0)

In [32]:
df.head()

animal name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        boar     1         0     0     1         0        0         1   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        1         1         1         0     0     4     0         0        1   
1        1         1         1         0     0     4     1         0        1   
2        1         1         0         0     1     0     1         0        0   
3        1         1         1         0     0     4     0         0        1   
4        1         1         1         0     0     4     1         0        1   

   type  
0     1  
1     1  
2     4  
3     1  
4     1

In [33]:
len(df)

101

In [34]:
df.shape

(101, 18)

In [35]:
df.drop('animal name',inplace=True,axis=1)

In [36]:
df.head()

hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  backbone  \
0     1         0     0     1         0        0         1        1         1   
1     1         0     0     1         0        0         0        1         1   
2     0         0     1     0         0        1         1        1         1   
3     1         0     0     1         0        0         1        1         1   
4     1         0     0     1         0        0         1        1         1   

   breathes  venomous  fins  legs  tail  domestic  catsize  type  
0         1         0     0     4     0         0        1     1  
1         1         0     0     4     1         0        1     1  
2         0         0     1     0     1         0        0     4  
3         1         0     0     4     0         0        1     1  
4         1         0     0     4     1         0        1     1

In [37]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [38]:
y

array([1, 1, 4, 1, 1, 1, 1, 4, 4, 1, 1, 2, 4, 7, 7, 7, 2, 1, 4, 1, 2, 2,
       1, 2, 6, 5, 5, 1, 1, 1, 6, 1, 1, 2, 4, 1, 1, 2, 4, 6, 6, 2, 6, 2,
       1, 1, 7, 1, 1, 1, 1, 6, 5, 7, 1, 1, 2, 2, 2, 2, 4, 4, 3, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 7, 4, 1, 1, 3, 7, 2, 2, 3, 7, 4, 2, 1, 7, 4, 2,
       6, 5, 3, 3, 4, 1, 1, 2, 1, 6, 1, 7, 2], dtype=int64)

In [39]:
from sklearn.preprocessing import Imputer

In [40]:
imputer = Imputer(missing_values='NaN', strategy ='most_frequent',axis=0) # creating a object of class imputer
imputer = imputer.fit(x[:,2:]) # fitting the imputer on the data
x[:,2:] = imputer.transform(x[:,2:]) # finally replacing the missing values

In [41]:
x=x[:,2:]


## Splitting the data

In [42]:
from sklearn.cross_validation import train_test_split

In [43]:
X_train,x_test , Y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=0) # do not change the sequence of variables

## Apply different Support Vector Kernels

In [44]:
from sklearn.svm import SVC

svm_classifier1 = SVC(kernel = 'linear', random_state = 0)
svm_classifier1.fit(X_train, Y_train)

# Predicting the Test set results
svm_pred1 = svm_classifier1.predict(x_test)

svm_cm = confusion_matrix(y_test, svm_pred1)
print(svm_cm)

[[11  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0]
 [ 0  1  0  1  0  0  0]
 [ 0  0  0  7  0  0  0]
 [ 0  0  0  0  1  0  0]
 [ 0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  2]]


In [45]:

svm_classifier2 = SVC(kernel = 'rbf', random_state = 0)
svm_classifier2.fit(X_train, Y_train)

# Predicting the Test set results
svm_pred2= svm_classifier2.predict(x_test)

svm_cm = confusion_matrix(y_test, svm_pred2)
print(svm_cm)

[[11  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0]
 [ 0  0  0  2  0  0  0]
 [ 0  0  0  7  0  0  0]
 [ 1  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  2]]


In [46]:
svm_classifier3 = SVC(kernel = 'poly', random_state = 0)
svm_classifier3.fit(X_train, Y_train)

# Predicting the Test set results
svm_pred3= svm_classifier3.predict(x_test)

svm_cm = confusion_matrix(y_test, svm_pred3)
print(svm_cm)

[[11  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0]
 [ 2  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0]
 [ 0  0  0  0  1  0  0]
 [ 0  0  0  0  0  2  0]
 [ 1  0  0  0  0  0  1]]


In [47]:
svm_classifier4 = SVC(kernel = 'sigmoid', random_state = 0)
svm_classifier4.fit(X_train, Y_train)

# Predicting the Test set results
svm_pred4 = svm_classifier4.predict(x_test)

svm_cm = confusion_matrix(y_test, svm_pred4)
print(svm_cm)


[[11  0  0  0  0  0  0]
 [ 1  5  0  0  0  0  0]
 [ 0  0  0  2  0  0  0]
 [ 0  0  0  7  0  0  0]
 [ 1  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0]
 [ 0  2  0  0  0  0  0]]


In [49]:
y_score.shape

(31, 7)

In [50]:
#accuracy before cross validation
from sklearn.metrics import accuracy_score
print('score=', accuracy_score(y_test,svm_pred1))
print('score=', accuracy_score(y_test,svm_pred2))
print('score=', accuracy_score(y_test,svm_pred3))
print('score=', accuracy_score(y_test,svm_pred4))

score= 0.9354838709677419
score= 0.9032258064516129
score= 0.9032258064516129
score= 0.7419354838709677


## K Cross Validation where K=5

In [51]:
#k cross validation
from sklearn.model_selection import cross_val_score
accuracy1=cross_val_score(estimator=svm_classifier1,X=X_train, y=Y_train,cv=5) #linear kernel
accuracy2=cross_val_score(estimator=svm_classifier2,X=X_train, y=Y_train,cv=5) #rbf
accuracy3=cross_val_score(estimator=svm_classifier3,X=X_train, y=Y_train,cv=5)#poly
accuracy4=cross_val_score(estimator=svm_classifier4,X=X_train, y=Y_train,cv=5)#sigmoid


C:\Users\Killerbird\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 3 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)
C:\Users\Killerbird\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 3 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)
C:\Users\Killerbird\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 3 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)
C:\Users\Killerbird\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 3 members, whic

In [52]:
print(accuracy1)
print(accuracy2)
print(accuracy3)
print(accuracy4)

[0.88235294 0.93333333 0.86666667 1.         1.        ]
[0.88235294 0.86666667 0.66666667 1.         1.        ]
[0.76470588 0.8        0.53333333 0.83333333 0.90909091]
[0.52941176 0.66666667 0.53333333 0.75       0.81818182]


In [53]:
print(accuracy1.mean())
print(accuracy2.mean())
print(accuracy3.mean())
print(accuracy4.mean())

0.9364705882352942
0.8831372549019608
0.7680926916221035
0.6595187165775401


## Applying grid search for optimal parameters

In [54]:
## applying grid search
from sklearn.model_selection import GridSearchCV

parameters1=[{'C': [1,10,100,1000], 'kernel': ['linear']}]
          
            
grid_search1=GridSearchCV(estimator=svm_classifier1,
                         param_grid=parameters1,
                        scoring='accuracy',
                        cv=5,
                        )
grid_search1=grid_search1.fit(X_train,Y_train)
best_accuracy1=grid_search1.best_score_
best_accuracy1


C:\Users\Killerbird\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 3 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


0.9285714285714286

In [55]:
parameters2=[{'C': [1,10,100,1000], 'kernel': ['rbf'],'gamma':[0.5,0.1,0.01,0.001,0.0001]}]
grid_search2=GridSearchCV(estimator=svm_classifier2,
                         param_grid=parameters2,
                        scoring='accuracy',
                        cv=5,
                        )
grid_search2=grid_search2.fit(X_train,Y_train)
best_accuracy2=grid_search2.best_score_
best_accuracy2
    

C:\Users\Killerbird\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 3 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


0.9285714285714286

In [56]:
parameters3=[{'C': [1,10,100,1000], 'kernel': ['poly'],'gamma':[0.5,0.1,0.01,0.001,0.0001]}]
grid_search3=GridSearchCV(estimator=svm_classifier3,
                         param_grid=parameters3,
                        scoring='accuracy',
                        cv=5,
                        )
grid_search3=grid_search3.fit(X_train,Y_train)
best_accuracy3=grid_search3.best_score_
best_accuracy3
    

C:\Users\Killerbird\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 3 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


0.9285714285714286

In [57]:
parameters4=[{'C': [1,10,100,1000], 'kernel': ['sigmoid'],'gamma':[0.5,0.1,0.01,0.001,0.0001]}]
grid_search4=GridSearchCV(estimator=svm_classifier4,
                         param_grid=parameters4,
                        scoring='accuracy',
                        cv=5,
                        )
grid_search4=grid_search4.fit(X_train,Y_train)
best_accuracy4=grid_search4.best_score_
best_accuracy4

C:\Users\Killerbird\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 3 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


0.9428571428571428

In [58]:
# final accuracies after setting up hyperparameters
print(best_accuracy1)
print(best_accuracy2)
print(best_accuracy3)
print(best_accuracy4)

0.9285714285714286
0.9285714285714286
0.9285714285714286
0.9428571428571428


In [64]:
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import classification_report
print(classification_report(y_test,svm_pred1))
print(classification_report(y_test,svm_pred2))
print(classification_report(y_test,svm_pred3))
print(classification_report(y_test,svm_pred4))




             precision    recall  f1-score   support

          1       1.00      1.00      1.00        11
          2       0.86      1.00      0.92         6
          3       0.00      0.00      0.00         2
          4       0.88      1.00      0.93         7
          5       1.00      1.00      1.00         1
          6       1.00      1.00      1.00         2
          7       1.00      1.00      1.00         2

avg / total       0.88      0.94      0.91        31

             precision    recall  f1-score   support

          1       0.92      1.00      0.96        11
          2       1.00      1.00      1.00         6
          3       0.00      0.00      0.00         2
          4       0.78      1.00      0.88         7
          5       0.00      0.00      0.00         1
          6       1.00      1.00      1.00         2
          7       1.00      1.00      1.00         2

avg / total       0.82      0.90      0.86        31

             precision    recall  f1-sco

C:\Users\Killerbird\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [66]:
print('Average precision value for linear kernel is :',0.88)
print('Average precision value for Radial basis kernel is :',0.82)
print('Average precision value for polynimial kernel is :',0.86)
print('Average precision value for sigmoid kernel is :',0.58)


Average precision value for linear kernel is : 0.88
Average precision value for Radial basis kernel is : 0.82
Average precision value for polynimial kernel is : 0.86
Average precision value for sigmoid kernel is : 0.58
