In [36]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import StratifiedKFold


In [8]:
df = pd.read_csv('zoo.csv',header=0)

In [9]:
df.head()

animal name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        boar     1         0     0     1         0        0         1   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        1         1         1         0     0     4     0         0        1   
1        1         1         1         0     0     4     1         0        1   
2        1         1         0         0     1     0     1         0        0   
3        1         1         1         0     0     4     0         0        1   
4        1         1         1         0     0     4     1         0        1   

   type  
0     1  
1     1  
2     4  
3     1  
4     1

In [10]:
len(df)

101

In [12]:
df.drop('animal name',inplace=True,axis=1)

In [13]:
df.head()

hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  backbone  \
0     1         0     0     1         0        0         1        1         1   
1     1         0     0     1         0        0         0        1         1   
2     0         0     1     0         0        1         1        1         1   
3     1         0     0     1         0        0         1        1         1   
4     1         0     0     1         0        0         1        1         1   

   breathes  venomous  fins  legs  tail  domestic  catsize  type  
0         1         0     0     4     0         0        1     1  
1         1         0     0     4     1         0        1     1  
2         0         0     1     0     1         0        0     4  
3         1         0     0     4     0         0        1     1  
4         1         0     0     4     1         0        1     1

In [15]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [16]:
x

array([[1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 1, 0, 1],
       [0, 0, 1, ..., 1, 0, 0],
       ...,
       [1, 0, 0, ..., 1, 0, 1],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 1, 0, 0]], dtype=int64)

In [17]:
y

array([1, 1, 4, 1, 1, 1, 1, 4, 4, 1, 1, 2, 4, 7, 7, 7, 2, 1, 4, 1, 2, 2,
       1, 2, 6, 5, 5, 1, 1, 1, 6, 1, 1, 2, 4, 1, 1, 2, 4, 6, 6, 2, 6, 2,
       1, 1, 7, 1, 1, 1, 1, 6, 5, 7, 1, 1, 2, 2, 2, 2, 4, 4, 3, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 7, 4, 1, 1, 3, 7, 2, 2, 3, 7, 4, 2, 1, 7, 4, 2,
       6, 5, 3, 3, 4, 1, 1, 2, 1, 6, 1, 7, 2], dtype=int64)

In [18]:
from sklearn.preprocessing import Imputer

In [19]:
imputer = Imputer(missing_values='NaN', strategy ='most_frequent',axis=0) # creating a object of class imputer
imputer = imputer.fit(x[:,:]) # fitting the imputer on the data
x[:,:] = imputer.transform(x[:,:]) # finally replacing the missing values

In [20]:
from sklearn.cross_validation import train_test_split

D:\anaconda\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [38]:
X_train,x_test , Y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=0) # do not change the sequence of variables

In [39]:

from sklearn.svm import SVC
svm_classifier = SVC(kernel = 'rbf', random_state = 0)
svm_classifier.fit(X_train, Y_train)

# Predicting the Test set results
svm_pred = svm_classifier.predict(x_test)

svm_cm = confusion_matrix(y_test, svm_pred)
print(svm_cm)

[[11  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0]
 [ 0  0  0  2  0  0  0]
 [ 0  0  0  7  0  0  0]
 [ 0  0  0  0  1  0  0]
 [ 0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  2]]


In [40]:
svm_classifier = SVC(kernel = 'linear', random_state = 0)
svm_classifier.fit(X_train, Y_train)

# Predicting the Test set results
svm_pred = svm_classifier.predict(x_test)

svm_cm = confusion_matrix(y_test, svm_pred)
print(svm_cm)

[[11  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0]
 [ 0  0  1  1  0  0  0]
 [ 0  0  0  7  0  0  0]
 [ 0  0  0  0  1  0  0]
 [ 0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  2]]


In [41]:
svm_classifier = SVC(kernel = 'poly', random_state = 0)
svm_classifier.fit(X_train, Y_train)

# Predicting the Test set results
svm_pred = svm_classifier.predict(x_test)

svm_cm = confusion_matrix(y_test, svm_pred)
print(svm_cm)

[[11  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0]
 [ 2  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0]
 [ 0  0  0  0  1  0  0]
 [ 0  0  0  0  0  2  0]
 [ 1  0  0  0  0  0  1]]


In [42]:
svm_classifier = SVC(kernel = 'sigmoid', random_state = 0)
svm_classifier.fit(X_train, Y_train)

# Predicting the Test set results
svm_pred = svm_classifier.predict(x_test)

svm_cm = confusion_matrix(y_test, svm_pred)
print(svm_cm)

[[11  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0]
 [ 0  0  0  2  0  0  0]
 [ 0  0  0  7  0  0  0]
 [ 1  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0]
 [ 0  2  0  0  0  0  0]]
